CREATE TABLE `categories` (
	`id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '카테고리ID',
	`name` VARCHAR(255) NOT NULL COMMENT '카테고리 이름' COLLATE 'utf8mb4_unicode_ci',
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
	PRIMARY KEY (`id`)
)
COMMENT='카테고리 정보'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;
