CREATE TABLE `magazine` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '매거진ID',
	`title` VARCHAR(255) NOT NULL COMMENT '제목' COLLATE 'utf8mb4_unicode_ci',
	`content` TEXT NOT NULL COMMENT '내용' COLLATE 'utf8mb4_unicode_ci',
	`author_id` INT(10) UNSIGNED NOT NULL COMMENT '작성자ID',
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
	PRIMARY KEY (`id`)
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;
