CREATE TABLE `magazines` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '매거진ID',
	`category_id` INT(10) UNSIGNED NOT NULL COMMENT '카테고리ID',
	`user_id` INT(10) UNSIGNED NOT NULL COMMENT '작성자ID',
	`file_id` INT(10) UNSIGNED NOT NULL COMMENT '대표이미지ID',
	`title` VARCHAR(255) NOT NULL COMMENT '제목' COLLATE 'utf8mb4_unicode_ci',
	`content` MEDIUMTEXT NOT NULL COMMENT '내용' COLLATE 'utf8mb4_unicode_ci',
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
	`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
	PRIMARY KEY (`id`)
)
COMMENT='매거진'
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;
